FROM python:buster

COPY docker/requirements-slack.txt requirements.txt

RUN pip3 install -r /requirements.txt

COPY miles_slack /miles_slack

ENV LANG=C.UTF-8

CMD [ "python3", "-c", "from miles_slack.main import main; main()" ]
